# Author:https://github.com/Repcz
# TG:https://t.me/RepczChannel
# 以 ';' 或 '#' 或 '//' 开头的配置文件行为注释行
#
# 最后更新时间: 2023/5/15
#
# ================

#port: 7890           # HTTP 代理端口
#socks-port: 7891     # SOCKS5 代理端口
#redir-port: 7892     # Linux 和 macOS 的 redir 代理端口
mixed-port: 7893      # 混合端口 HTTP和SOCKS5用一个端口
allow-lan: true       # 允许局域网的连接（可用来共享代理）
bind-address: "*"     # 仅在将allow-lan设置为true时适用
                      # #"*": 绑定所有IP地址
ipv6: false           # 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录
mode: rule            # 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
log-level: info       # 设置日志输出级别 (5 个级别：silent / error / warning / info / debug）
external-controller: 127.0.0.1:9090   #外部控制器,可以使用 RESTful API 来控制你的 clash 内核

hosts:
# '*.clash.dev': 127.0.0.1
# '.dev': 127.0.0.1
# 'alpha.clash.dev': '::1'
# test.com: [1.1.1.1, 2.2.2.2]
# clash.lan: clash # clash 为特别字段，将加入本地所有网卡的地址
# baidu.com: google.com # 只允许配置一个别名
  # > IPv6
  "ip6-localhost": "::1" # IPv6 Localhost
  "ip6-loopback": "::1" # IPv6 Loopback
  "ip6-localnet": "fe00::0" # IPv6 Link-Local
  "ip6-mcastprefix": "ff00::0" # IPv6 Multicast
  "ip6-allnodes": "ff02::1" # IPv6 All Nodes
  "ip6-allrouters": "ff02::2" # IPv6 All Routers
  "ip6-allhosts": "ff02::3" # IPv6 All Hosts
  # > Firebase Cloud Messaging
  "talk.google.com": "108.177.125.188" # Firebase Cloud Messaging
  "mtalk.google.com": "108.177.125.188" # Firebase Cloud Messaging
  "alt1-mtalk.google.com": "3.3.3.3" # Firebase Cloud Messaging
  "alt2-mtalk.google.com": "3.3.3.3" # Firebase Cloud Messaging
  "alt3-mtalk.google.com": "74.125.200.188" # Firebase Cloud Messaging
  "alt4-mtalk.google.com": "74.125.200.188" # Firebase Cloud Messaging
  "alt5-mtalk.google.com": "3.3.3.3" # Firebase Cloud Messaging
  "alt6-mtalk.google.com": "3.3.3.3" # Firebase Cloud Messaging
  "alt7-mtalk.google.com": "74.125.200.188" # Firebase Cloud Messaging
  "alt8-mtalk.google.com": "3.3.3.3" # Firebase Cloud Messaging

dns:
  enable: true             # 关闭将使用系统 DNS
  ipv6: false              # IPV6解析开关；如果为false，将返回ipv6结果为空
  enhanced-mode: fake-ip   # 模式：redir-host或fake-ip
  listen: 0.0.0.0:53       # DNS监听地址
  default-nameserver:      # 解析非IP的dns用的dns服务器,只支持纯IP
     - 223.5.5.5
     - 119.29.29.29
  fake-ip-range: 198.18.0.1/16    # Fake-IP解析地址池
  fake-ip-filter:          # fake ip 白名单列表,以下地址不会下发fakeip映射用于连接
     - '*.lan'
     - localhost.ptlogin2.qq.com
     - '+.srv.nintendo.net'
     - '+.stun.playstation.net'
     - '+.msftconnecttest.com'
     - '+.msftncsi.com'
     - '+.xboxlive.com'
     - 'msftconnecttest.com'
     - 'xbox.*.microsoft.com'
     - '*.battlenet.com.cn'
     - '*.battlenet.com'
     - '*.blzstatic.cn'
     - '*.battle.net'
     - '*.mcdn.bilivideo.cn'
  nameserver:             # 默认DNS服务器，支持udp/tcp/dot/doh/doq
     - 223.5.5.5
     - 119.29.29.29
  fallback:               # 解析国外域名的DNS服务器
     - https://doh.pub/dns-query
     - https://dns.alidns.com/dns-query
  fallback-filter:        # 配置 fallback 使用条件
    geoip: true           # 配置是否使用 geoip
    geoip-code: CN        # 当 nameserver 域名的 IP 查询 geoip 库为 CN 时，不使用 fallback 中的 DNS 查询结果
    ipcidr:               # 在这个网段内的 IP 地址会被考虑为被污染的 IP
      - 240.0.0.0/4
    domain:               # 这些域名被视为已污染,匹配到这些域名,会直接使用fallback解析,不去使用nameserver
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
