mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090

dns:
  enable: true 
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip  
  fake-ip-range: 198.18.0.1/16 
  fake-ip-filter:
     - '*.lan'
     - localhost.ptlogin2.qq.com
     - '+.srv.nintendo.net'
     - '+.stun.playstation.net'
     - '+.msftconnecttest.com'
     - '+.msftncsi.com'
     - '+.xboxlive.com'
     - 'msftconnecttest.com'
     - 'xbox.*.microsoft.com'
     - '*.battlenet.com.cn'
     - '*.battlenet.com'
     - '*.blzstatic.cn'
     - '*.battle.net'
  nameserver:
     - 223.5.5.5
     - 180.76.76.76
     - 119.29.29.29
     - 117.50.11.11
     - 117.50.10.10
     - 114.114.114.114 # 114DNS
     - https://dns.alidns.com/dns-query
     - https://doh.360.cn/dns-query
  fallback:
     - 8.8.8.8
     - 1.1.1.1
     - tls://dns.rubyfish.cn:853
     - tls://1.0.0.1:853
     - tls://dns.google:853
     - https://dns.rubyfish.cn/dns-query
     - https://cloudflare-dns.com/dns-query
     - https://dns.google/dns-query
  fallback-filter:
     geoip: true
     ipcidr:
       - 240.0.0.0/4
