# 基于[@JohnsonRan](https://github.com/JohnsonRan/CRules/blob/master/config/GeneralClashConfig.yml)修改
# Author：https://github.com/Repcz
#
# 以 ';' 或 '#' 或 '//' 开头的配置文件行为注释行
#
# 最后更新时间: 2023/4/19
#
# ================

port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
geodata-mode: true
tcp-concurrent: true
allow-lan: true
bind-address: "*"
ipv6: false
mode: rule
log-level: info
external-controller: 0.0.0.0:9090

geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  #mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
  
profile:
  store-selected: true
  store-fake-ip: true
  
sniffer:
  enable: true
  parse-pure-ip: true
  force-domain:
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssott.com"
  - 'google.com'
  skip-domain:
  - "+.apple.com"
  - Mijia Cloud
  - "+.jd.com"
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
      
tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true
        
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
     - '*.lan'
     - localhost.ptlogin2.qq.com
     - '+.srv.nintendo.net'
     - '+.stun.playstation.net'
     - '+.msftconnecttest.com'
     - '+.msftncsi.com'
     - '+.xboxlive.com'
     - 'msftconnecttest.com'
     - 'xbox.*.microsoft.com'
     - '*.battlenet.com.cn'
     - '*.battlenet.com'
     - '*.blzstatic.cn'
     - '*.battle.net'
     - '*.mcdn.bilivideo.cn'
  nameserver:
     - 223.5.5.5
     - 119.29.29.29
     - 114.114.114.114
  fallback:
     - https://cloudflare-dns.com/dns-query
     - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr: 
      - 240.0.0.0/4
    domain: 
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
   proxy-server-nameserver:
      - 223.5.5.5
experimental:
  ignore-resolve-fail: true
