# 基于[@JohnsonRan](https://github.com/JohnsonRan/CRules/blob/master/config/GeneralClashConfig.yml)修改
# Author:https://github.com/Repcz
# TG:https://t.me/RepczChannel
# 以 ';' 或 '#' 或 '//' 开头的配置文件行为注释行
#
# 最后更新时间: 2023/5/4
#
# ================

port: 7890           # HTTP 代理端口
#socks-port: 7891     # SOCKS5 代理端口
#redir-port: 7892     # Linux 和 macOS 的 redir 代理端口
mixed-port: 7893      # 混合端口 HTTP和SOCKS5用一个端口
geodata-mode: true    #【Meta专属】使用geoip.dat数据库(默认：false使用mmdb数据库)
tcp-concurrent: true  #【Meta专属】TCP 并发连接所有 IP, 将使用最快握手的 TCP
allow-lan: true       # 允许局域网的连接（可用来共享代理）
bind-address: "*"     # 仅在将allow-lan设置为true时适用
                      # #"*": 绑定所有IP地址
ipv6: false           # 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录
mode: rule            # 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
log-level: info       # 设置日志输出级别 (5 个级别：silent / error / warning / info / debug）
external-controller: 127.0.0.1:9090   #外部控制器,可以使用 RESTful API 来控制你的 clash 内核

geox-url:             #自定义 geodata url
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  #mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
  
profile:
  store-selected: true # 存储 select 选择记录
  store-fake-ip: true  # 持久化 fake-ip
  
sniffer:               # 嗅探域名 可选配置
  enable: true
  parse-pure-ip: true  # 是否使用嗅探结果作为实际访问，默认 true
  sniff:
    TLS:               # TLS 默认如果不配置 ports 默认嗅探 443
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
  force-domain:        # 强制对此域名进行嗅探
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssott.com"
  - 'google.com'
  sniffing:            # 需要嗅探协议
    - tls
    - http
      
tun:                   # Tun 配置
  enable: true
  stack: system        # 可选： system/gvisor/lwip
                       # tun模式堆栈,如无使用问题,建议使用 system 栈;
                       # MacOS 用户推荐 gvisor栈,IOS无法使用system栈
  dns-hijack:          # dns劫持,一般设置为 any:53 即可, 即劫持所有53端口的udp流量
    - 'any:53'
# strict_route: true   # 将所有连接路由到tun来防止泄漏，但你的设备将无法其他设备被访问
  auto-route: true     # 自动设置全局路由，可以自动将全局流量路由进入tun网卡。
  auto-detect-interface: true   # 自动识别出口网卡
        
dns:
  enable: true
  ipv6: false
  prefer-h3: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
     - '*.lan'
     - localhost.ptlogin2.qq.com
     - '+.srv.nintendo.net'
     - '+.stun.playstation.net'
     - '+.msftconnecttest.com'
     - '+.msftncsi.com'
     - '+.xboxlive.com'
     - 'msftconnecttest.com'
     - 'xbox.*.microsoft.com'
     - '*.battlenet.com.cn'
     - '*.battlenet.com'
     - '*.blzstatic.cn'
     - '*.battle.net'
     - '*.wuhanrt.com'
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - '!CN'
    ipcidr: 
      - 240.0.0.0/4
    domain: 
      #- '+.google.com'
      - '+.github.com'
      - '+.youtube.com'  
      - "+.bing.com"
      - "+.bing.net"
      - "+.microsoft.com"
      - "+.microsoftapp.net"
      - "+.msn.com"
      - "+.trafficmanager.com"

  default-nameserver:
     - 119.29.29.29
     - 114.114.114.114
  nameserver:
     - https://doh.pub/dns-query
     - 192.168.1.1
     - tls://223.5.5.5:853
     - https://dns.alidns.com/dns-query
     - quic://dns.adguard.com:784
  fallback:
     - https://doh.pub/dns-query
     - https://dns.google/dns-query
     - https://cloudflare-dns.com/dns-query
  proxy-server-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - https://doh.apad.pro/dns-query

